version: '3.8'

x-common-service: &common-service
  build:
    dockerfile: Dockerfile
    args:
      WWWGROUP: '${WWWGROUP}'
  image: sail-8.3/app
  extra_hosts:
    - 'host.docker.internal:host-gateway'
  environment:
    WWWUSER: '${WWWUSER}'
    LARAVEL_SAIL: 1
    XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    IGNITION_LOCAL_SITES_PATH: '${PWD}'
  volumes:
    - './:/var/www/html'
  networks:
    - common_network

  x-common-db-service: &common-db-service
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './api-gateway/sail-mysql:/var/lib/mysql'
      - './api-gateway/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - common_network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

services:
  api-gateway:
    <<: *common-service
    build:
      context: ./api-gateway/vendor/laravel/sail/runtimes/8.3
    container_name: api-gateway
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - './api-gateway:/var/www/html'

  payment-service:
    <<: *common-service
    build:
      context: ./payment-service/vendor/laravel/sail/runtimes/8.3
    container_name: payment-service
    ports:
      - '82:80'
      - '${VITE_PORT:-5174}:${VITE_PORT:-5173}'
    volumes:
      - './payment-service:/var/www/html'

  finansbank-service:
    <<: *common-service
    build:
      context: ./finansbank-service/vendor/laravel/sail/runtimes/8.3
    container_name: finansbank-service
    ports:
      - '85:80'
      - '${VITE_PORT:-5179}:${VITE_PORT:-5173}'
    volumes:
      - './finansbank-service:/var/www/html'

  garanti-service:
    <<: *common-service
    build:
      context: ./garanti-service/vendor/laravel/sail/runtimes/8.3
    container_name: garanti-service
    ports:
      - '87:80'
      - '${VITE_PORT:-5184}:${VITE_PORT:-5173}'
    volumes:
      - './garanti-service:/var/www/html'

  hsbc-service:
    <<: *common-service
    build:
      context: ./hsbc-service/vendor/laravel/sail/runtimes/8.3
    container_name: hsbc-service
    ports:
      - '86:80'
      - '${VITE_PORT:-5181}:${VITE_PORT:-5173}'
    volumes:
      - './hsbc-service:/var/www/html'

  auth-db:
    <<: *common-db-service
    container_name: auth-db
    ports:
      - '3306:3306'
    volumes:
      - './api-gateway/sail-mysql:/var/lib/mysql'
      - './api-gateway/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  payment-service-db:
    <<: *common-db-service
    container_name: payment-service-db
    ports:
      - '3310:3306'
    volumes:
      - './payment-service/sail-mysql:/var/lib/mysql'
      - './payment-service/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  finansbank-service-db:
    <<: *common-db-service
    container_name: finansbank-service-db
    ports:
      - '3311:3306'
    volumes:
      - './finansbank-service/sail-mysql:/var/lib/mysql'
      - './finansbank-service/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  garanti-service-db:
    <<: *common-db-service
    container_name: garanti-service-db
    ports:
      - '3313:3306'
    volumes:
      - './garanti-service/sail-mysql:/var/lib/mysql'
      - './garanti-service/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'

  hsbc-service-db:
    <<: *common-db-service
    container_name: hsbc-service-db
    ports:
      - '3314:3306'
    volumes:
      - './hsbc-service/sail-mysql:/var/lib/mysql'
      - './hsbc-service/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
networks:
  common_network:
    external: true

volumes:
  sail-mysql:
    driver: local

x-project:
  name: my_project
